// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDttB87tx2UmQnc8NEOlRw6SpXFs66XdAc',
    appId: '1:457121024706:web:d1a725f88a2fd0741ac95b',
    messagingSenderId: '457121024706',
    projectId: 'rizki-467b3',
    authDomain: 'rizki-467b3.firebaseapp.com',
    storageBucket: 'rizki-467b3.appspot.com',
    measurementId: 'G-LMCL12257N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3RDMghHg_pRiCm74YoHIB79-5mFjqHYw',
    appId: '1:457121024706:android:fe28bc9fdc2adc561ac95b',
    messagingSenderId: '457121024706',
    projectId: 'rizki-467b3',
    storageBucket: 'rizki-467b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyW1UmJLn7EGVdgoZFxRcRbgw2IG6q-Q4',
    appId: '1:457121024706:ios:9f706623a8845eae1ac95b',
    messagingSenderId: '457121024706',
    projectId: 'rizki-467b3',
    storageBucket: 'rizki-467b3.appspot.com',
    iosBundleId: 'com.example.companyProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyW1UmJLn7EGVdgoZFxRcRbgw2IG6q-Q4',
    appId: '1:457121024706:ios:9f706623a8845eae1ac95b',
    messagingSenderId: '457121024706',
    projectId: 'rizki-467b3',
    storageBucket: 'rizki-467b3.appspot.com',
    iosBundleId: 'com.example.companyProfile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDttB87tx2UmQnc8NEOlRw6SpXFs66XdAc',
    appId: '1:457121024706:web:f524a93058ed507d1ac95b',
    messagingSenderId: '457121024706',
    projectId: 'rizki-467b3',
    authDomain: 'rizki-467b3.firebaseapp.com',
    storageBucket: 'rizki-467b3.appspot.com',
    measurementId: 'G-G8TM3LQP4X',
  );
}
